export const APP_ERROR_CODE = "APP_ERROR" as const;
export const INVALID_INPUT_ERROR_CODE = "INVALID_INPUT" as const;
export const DATABASE_SCHEMA_TOO_NEW_ERROR_CODE = "DATABASE_SCHEMA_TOO_NEW" as const;

export const INVALID_URL_ERROR_CODE = "INVALID_URL" as const;
export const INVALID_LIBRARY_PATH_ERROR_CODE = "INVALID_LIBRARY_PATH" as const;
export const INVALID_DIRECTORY_PATH_ERROR_CODE = "INVALID_DIRECTORY_PATH" as const;
export const READ_DIR_FAILED_ERROR_CODE = "READ_DIR_FAILED" as const;
export const INVALID_MEDIA_PATH_ERROR_CODE = "INVALID_MEDIA_PATH" as const;
export const INVALID_THUMBNAIL_PATH_ERROR_CODE = "INVALID_THUMBNAIL_PATH" as const;
export const INVALID_TEMP_THUMBNAIL_PATH_ERROR_CODE = "INVALID_TEMP_THUMBNAIL_PATH" as const;

export const SOURCE_MEDIA_NOT_FOUND_ERROR_CODE = "SOURCE_MEDIA_NOT_FOUND" as const;
export const INVALID_SOURCE_MEDIA_ERROR_CODE = "INVALID_SOURCE_MEDIA" as const;
export const SOURCE_THUMBNAIL_NOT_FOUND_ERROR_CODE = "SOURCE_THUMBNAIL_NOT_FOUND" as const;
export const INVALID_SOURCE_THUMBNAIL_ERROR_CODE = "INVALID_SOURCE_THUMBNAIL" as const;
export const INVALID_THUMBNAIL_FILE_ERROR_CODE = "INVALID_THUMBNAIL_FILE" as const;
export const THUMBNAIL_NOT_SUPPORTED_FOR_AUDIO_ERROR_CODE =
    "THUMBNAIL_NOT_SUPPORTED_FOR_AUDIO" as const;

export const FFMPEG_NOT_FOUND_ERROR_CODE = "FFMPEG_NOT_FOUND" as const;
export const FFMPEG_FAILED_ERROR_CODE = "FFMPEG_FAILED" as const;
export const FFMPEG_EXEC_FAILED_ERROR_CODE = "FFMPEG_EXEC_FAILED" as const;

export const YT_DLP_NOT_FOUND_ERROR_CODE = "YT_DLP_NOT_FOUND" as const;
export const YT_DLP_METADATA_TIMEOUT_ERROR_CODE = "YT_DLP_METADATA_TIMEOUT" as const;
export const YT_DLP_DOWNLOAD_TIMEOUT_ERROR_CODE = "YT_DLP_DOWNLOAD_TIMEOUT" as const;
export const YT_DLP_THUMBNAIL_TIMEOUT_ERROR_CODE = "YT_DLP_THUMBNAIL_TIMEOUT" as const;
export const YT_DLP_DOWNLOAD_FAILED_ERROR_CODE = "YT_DLP_DOWNLOAD_FAILED" as const;
export const YT_DLP_DOWNLOAD_CANCELLED_ERROR_CODE = "YT_DLP_DOWNLOAD_CANCELLED" as const;
export const YT_DLP_THUMBNAIL_FAILED_ERROR_CODE = "YT_DLP_THUMBNAIL_FAILED" as const;
export const YT_DLP_METADATA_FAILED_ERROR_CODE = "YT_DLP_METADATA_FAILED" as const;
export const INVALID_FORMAT_ID_ERROR_CODE = "INVALID_FORMAT_ID" as const;
export const INVALID_RUN_ID_ERROR_CODE = "INVALID_RUN_ID" as const;

export const DESTINATION_ALREADY_EXISTS_ERROR_CODE = "DESTINATION_ALREADY_EXISTS" as const;
export const INVALID_LIBRARY_MIGRATION_ERROR_CODE = "INVALID_LIBRARY_MIGRATION" as const;
export const PATH_OUTSIDE_BASE_DIR_ERROR_CODE = "PATH_OUTSIDE_BASE_DIR" as const;

export const CHANNEL_ALREADY_EXISTS_ERROR_CODE = "CHANNEL_ALREADY_EXISTS" as const;
export const INVALID_YOUTUBE_HANDLE_ERROR_CODE = "INVALID_YOUTUBE_HANDLE" as const;
export const INVALID_CHANNEL_NAME_ERROR_CODE = "INVALID_CHANNEL_NAME" as const;
export const INVALID_CHANNEL_ID_ERROR_CODE = "INVALID_CHANNEL_ID" as const;
export const INVALID_MEDIA_CREATION_ARGUMENTS_ERROR_CODE =
    "INVALID_MEDIA_CREATION_ARGUMENTS" as const;
export const MEDIA_IMPORT_FAILED_ERROR_CODE = "MEDIA_IMPORT_FAILED" as const;
export const VIDEO_ALREADY_EXISTS_FOR_CHANNEL_ERROR_CODE =
    "VIDEO_ALREADY_EXISTS_FOR_CHANNEL" as const;
export const CHANNEL_NOT_FOUND_ERROR_CODE = "CHANNEL_NOT_FOUND" as const;
export const INVALID_YOUTUBE_VIDEO_ID_ERROR_CODE = "INVALID_YOUTUBE_VIDEO_ID" as const;
export const INVALID_MEDIA_TITLE_ERROR_CODE = "INVALID_MEDIA_TITLE" as const;
export const MEDIA_WITHOUT_YOUTUBE_SOURCE_ERROR_CODE = "MEDIA_WITHOUT_YOUTUBE_SOURCE" as const;
export const INVALID_YOUTUBE_COMMENTS_PAYLOAD_ERROR_CODE =
    "INVALID_YOUTUBE_COMMENTS_PAYLOAD" as const;
export const YOUTUBE_COMMENTS_EMPTY_REFRESH_ERROR_CODE =
    "YOUTUBE_COMMENTS_EMPTY_REFRESH" as const;

export const KNOWN_ERROR_CODES = [
    APP_ERROR_CODE,
    INVALID_INPUT_ERROR_CODE,
    DATABASE_SCHEMA_TOO_NEW_ERROR_CODE,
    INVALID_URL_ERROR_CODE,
    INVALID_LIBRARY_PATH_ERROR_CODE,
    INVALID_DIRECTORY_PATH_ERROR_CODE,
    READ_DIR_FAILED_ERROR_CODE,
    INVALID_MEDIA_PATH_ERROR_CODE,
    INVALID_THUMBNAIL_PATH_ERROR_CODE,
    INVALID_TEMP_THUMBNAIL_PATH_ERROR_CODE,
    SOURCE_MEDIA_NOT_FOUND_ERROR_CODE,
    INVALID_SOURCE_MEDIA_ERROR_CODE,
    SOURCE_THUMBNAIL_NOT_FOUND_ERROR_CODE,
    INVALID_SOURCE_THUMBNAIL_ERROR_CODE,
    INVALID_THUMBNAIL_FILE_ERROR_CODE,
    THUMBNAIL_NOT_SUPPORTED_FOR_AUDIO_ERROR_CODE,
    FFMPEG_NOT_FOUND_ERROR_CODE,
    FFMPEG_FAILED_ERROR_CODE,
    FFMPEG_EXEC_FAILED_ERROR_CODE,
    YT_DLP_NOT_FOUND_ERROR_CODE,
    YT_DLP_METADATA_TIMEOUT_ERROR_CODE,
    YT_DLP_DOWNLOAD_TIMEOUT_ERROR_CODE,
    YT_DLP_THUMBNAIL_TIMEOUT_ERROR_CODE,
    YT_DLP_DOWNLOAD_FAILED_ERROR_CODE,
    YT_DLP_DOWNLOAD_CANCELLED_ERROR_CODE,
    YT_DLP_THUMBNAIL_FAILED_ERROR_CODE,
    YT_DLP_METADATA_FAILED_ERROR_CODE,
    INVALID_FORMAT_ID_ERROR_CODE,
    INVALID_RUN_ID_ERROR_CODE,
    DESTINATION_ALREADY_EXISTS_ERROR_CODE,
    INVALID_LIBRARY_MIGRATION_ERROR_CODE,
    PATH_OUTSIDE_BASE_DIR_ERROR_CODE,
    CHANNEL_ALREADY_EXISTS_ERROR_CODE,
    INVALID_YOUTUBE_HANDLE_ERROR_CODE,
    INVALID_CHANNEL_NAME_ERROR_CODE,
    INVALID_CHANNEL_ID_ERROR_CODE,
    INVALID_MEDIA_CREATION_ARGUMENTS_ERROR_CODE,
    MEDIA_IMPORT_FAILED_ERROR_CODE,
    VIDEO_ALREADY_EXISTS_FOR_CHANNEL_ERROR_CODE,
    CHANNEL_NOT_FOUND_ERROR_CODE,
    INVALID_YOUTUBE_VIDEO_ID_ERROR_CODE,
    INVALID_MEDIA_TITLE_ERROR_CODE,
    MEDIA_WITHOUT_YOUTUBE_SOURCE_ERROR_CODE,
    INVALID_YOUTUBE_COMMENTS_PAYLOAD_ERROR_CODE,
    YOUTUBE_COMMENTS_EMPTY_REFRESH_ERROR_CODE,
] as const;

export type KnownErrorCode = typeof KNOWN_ERROR_CODES[number];